pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME##docker-}"
      tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      event:
        - push
branches:
  - master
